## Prime number in range
numpy,pandas, seaborn , matplotlib, scikitlearn, scipy, mlxtend


In [1]:
l = int(input("Enter lower range  : "))
h = int(input("Enter higher range : "))

prime = []
for i in range(l, h + 1):
    if i > 1:
        for j in range(2, int(i ** 0.5) + 1):
            if i % j == 0:
                break
        else:
            prime.append(i)

print(f"Prime numbers in range ({l},{h}) : {prime}")

Prime numbers in range (1,10) : [2, 3, 5, 7]


### Matrix multiplication

In [3]:
import numpy as np 

a = [[1,0,0],
     [0,1,0],
     [0,0,1]]

b = [[1,2,32],
     [4,1,5],
     [0,0,1]]
print(np.dot(a,b))

[[ 1  2 32]
 [ 4  1  5]
 [ 0  0  1]]


# List slicing

In [4]:
l = [1,2,3,4,5]
print(f"l[1:4] : {l[1:4]}")
print(f"l[-3:-1] : {l[-3:-1]}")
print(f"l[1:-1] : {l[1:-1]}")

l[1:4] : [2, 3, 4]
l[-3:-1] : [3, 4]
l[1:-1] : [2, 3, 4]
