* ## Required libraries installation

In [1]:
# %pip install numpy pandas matplotlib mlxtend scikit-learn

In [2]:
import numpy as np
import pandas as pd 

In [3]:
df = pd.read_csv("placement.xls")
df

,Unnamed: 0,cgpa,iq,placement
0,0,6.8,123.0,1
1,1,5.9,106.0,0
2,2,5.3,121.0,0
3,3,7.4,132.0,1
4,4,5.8,142.0,0
...,...,...,...,...
95,95,4.3,200.0,0
96,96,4.4,42.0,0
97,97,6.7,182.0,1
98,98,6.3,103.0,1


In [4]:
df.head(10)

,Unnamed: 0,cgpa,iq,placement
0,0,6.8,123.0,1
1,1,5.9,106.0,0
2,2,5.3,121.0,0
3,3,7.4,132.0,1
4,4,5.8,142.0,0
5,5,7.1,48.0,1
6,6,5.7,143.0,0
7,7,5.0,63.0,0
8,8,6.1,156.0,0
9,9,5.1,66.0,0


In [5]:
df.tail(5)

,Unnamed: 0,cgpa,iq,placement
95,95,4.3,200.0,0
96,96,4.4,42.0,0
97,97,6.7,182.0,1
98,98,6.3,103.0,1
99,99,6.2,113.0,1


In [6]:
df.nunique()

Unnamed: 0    100
cgpa           39
iq             71
placement       2
dtype: int64

In [7]:
df["placement"].unique()

array([1, 0])

In [8]:
df.shape

(100, 4)

In [9]:
df.drop(columns=["Unnamed: 0"],inplace=True)

In [10]:
df

,cgpa,iq,placement
0,6.8,123.0,1
1,5.9,106.0,0
2,5.3,121.0,0
3,7.4,132.0,1
4,5.8,142.0,0
...,...,...,...
95,4.3,200.0,0
96,4.4,42.0,0
97,6.7,182.0,1
98,6.3,103.0,1


In [11]:
# df.to_csv("updated_placement.csv",index=False)

In [12]:
new_df = pd.read_csv("updated_placement.csv")
new_df

,cgpa,iq,placement
0,6.8,123.0,1
1,5.9,106.0,0
2,5.3,121.0,0
3,7.4,132.0,1
4,5.8,142.0,0
...,...,...,...
95,4.3,200.0,0
96,4.4,42.0,0
97,6.7,182.0,1
98,6.3,103.0,1


In [13]:
new_df["placement_chances"] = np.where(new_df["cgpa"] > 6.5,True,False)

In [14]:
new_df

,cgpa,iq,placement,placement_chances
0,6.8,123.0,1,True
1,5.9,106.0,0,False
2,5.3,121.0,0,False
3,7.4,132.0,1,True
4,5.8,142.0,0,False
...,...,...,...,...
95,4.3,200.0,0,False
96,4.4,42.0,0,False
97,6.7,182.0,1,True
98,6.3,103.0,1,False


In [15]:
cgpa = np.random.uniform(4,9.8,size=100).round(2)
iq = np.random.uniform(35,169,size=100).round(2)

In [16]:
cgpa

array([6.85, 8.93, 6.9 , 9.36, 7.27, 5.94, 8.03, 8.93, 5.21, 8.75, 7.11,
       8.36, 7.13, 6.5 , 6.25, 7.25, 7.04, 6.45, 4.32, 4.3 , 5.54, 4.62,
       5.56, 4.92, 7.84, 4.67, 8.12, 4.84, 8.37, 6.95, 9.28, 4.46, 8.29,
       5.9 , 5.76, 6.54, 9.11, 4.38, 8.14, 9.76, 9.76, 8.4 , 4.31, 5.69,
       5.94, 6.24, 6.91, 7.48, 9.35, 8.3 , 6.73, 7.25, 6.65, 9.16, 5.22,
       7.22, 6.85, 4.1 , 8.74, 6.49, 8.74, 9.4 , 5.93, 6.16, 5.12, 6.19,
       7.95, 5.89, 8.72, 9.14, 6.37, 9.59, 4.19, 5.06, 9.59, 7.1 , 4.86,
       6.28, 9.04, 6.67, 6.83, 5.64, 9.36, 7.48, 6.53, 5.97, 6.06, 6.62,
       6.37, 7.93, 5.88, 9.75, 4.8 , 9.19, 4.2 , 7.22, 7.4 , 9.36, 5.26,
       8.77])

In [17]:
iq

array([139.36, 116.7 , 119.73, 147.89, 160.49, 103.64, 156.79, 106.26,
       143.39,  47.01,  91.02, 147.31, 131.05, 155.82, 154.6 , 165.73,
        39.57, 118.17, 147.76, 120.07,  76.6 , 140.96,  40.74, 144.9 ,
        74.27, 128.31, 108.85, 156.8 ,  49.65,  57.98,  64.56, 117.02,
        57.12, 109.19,  51.08, 117.63, 137.64,  36.77,  63.61,  45.74,
        51.3 ,  89.13,  80.48, 114.68,  49.31, 163.63,  75.76,  76.58,
       104.67,  72.63, 138.85,  41.69,  82.41, 114.22, 102.27,  42.67,
        53.65,  79.56,  92.36,  95.55, 159.23,  85.62, 159.9 ,  69.48,
        43.26, 102.68,  97.82,  57.85, 148.69,  84.13,  53.89, 125.97,
       166.82, 139.01, 119.16, 104.07,  53.82,  86.43,  65.14,  97.13,
       151.6 ,  58.15, 113.23,  74.39, 158.85,  70.87, 140.35, 135.88,
        36.41,  87.19, 143.78,  98.28,  40.64,  98.14, 139.02,  92.37,
        52.82, 121.97, 144.42, 141.5 ])

In [18]:
new_data = pd.DataFrame({
    "cgpa":cgpa,
    "iq":iq
})
new_data

,cgpa,iq
0,6.85,139.36
1,8.93,116.70
2,6.90,119.73
3,9.36,147.89
4,7.27,160.49
...,...,...
95,7.22,92.37
96,7.40,52.82
97,9.36,121.97
98,5.26,144.42


In [19]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   cgpa    100 non-null    float64
 1   iq      100 non-null    float64
dtypes: float64(2)
memory usage: 1.7 KB


In [20]:
new_data["placement"] = np.where((new_data["cgpa"] > 7.4) | (new_data["iq"]>150),True,False)

In [21]:
new_data

,cgpa,iq,placement
0,6.85,139.36,False
1,8.93,116.70,True
2,6.90,119.73,False
3,9.36,147.89,True
4,7.27,160.49,True
...,...,...,...
95,7.22,92.37,False
96,7.40,52.82,False
97,9.36,121.97,True
98,5.26,144.42,False


In [22]:
# new_data.to_csv("new_placement.csv",index=False)

In [33]:
df2 = pd.read_csv("new_placement.csv")
df2.head()

,cgpa,iq,placement
0,4.17,60.51,False
1,6.48,125.18,False
2,5.02,111.90,False
3,7.94,45.60,True
4,6.60,130.31,False


In [30]:
df3 = pd.read_csv("train.csv")
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
